---
name: MooseX-AttributeHelpers
version: 0.02
author:
  - 'Stevan Little E<lt>stevan@iinteractive.comE<gt>'
abstract: Extend your attribute interfaces
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Moose: 0.24
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
provides:
  Moose::Meta::Attribute::Custom::Collection::Array:
    file: lib/MooseX/AttributeHelpers/Collection/Array.pm
  Moose::Meta::Attribute::Custom::Collection::Hash:
    file: lib/MooseX/AttributeHelpers/Collection/Hash.pm
  Moose::Meta::Attribute::Custom::Collection::List:
    file: lib/MooseX/AttributeHelpers/Collection/List.pm
  Moose::Meta::Attribute::Custom::Counter:
    file: lib/MooseX/AttributeHelpers/Counter.pm
  Moose::Meta::Attribute::Custom::Number:
    file: lib/MooseX/AttributeHelpers/Number.pm
  MooseX::AttributeHelpers:
    file: lib/MooseX/AttributeHelpers.pm
    version: 0.02
  MooseX::AttributeHelpers::Base:
    file: lib/MooseX/AttributeHelpers/Base.pm
    version: 0.02
  MooseX::AttributeHelpers::Collection:
    file: lib/MooseX/AttributeHelpers/Collection.pm
    version: 0.01
  MooseX::AttributeHelpers::Collection::Array:
    file: lib/MooseX/AttributeHelpers/Collection/Array.pm
    version: 0.01
  MooseX::AttributeHelpers::Collection::Hash:
    file: lib/MooseX/AttributeHelpers/Collection/Hash.pm
    version: 0.01
  MooseX::AttributeHelpers::Collection::List:
    file: lib/MooseX/AttributeHelpers/Collection/List.pm
    version: 0.01
  MooseX::AttributeHelpers::Counter:
    file: lib/MooseX/AttributeHelpers/Counter.pm
    version: 0.01
  MooseX::AttributeHelpers::Meta::Method::Provided:
    file: lib/MooseX/AttributeHelpers/Meta/Method/Provided.pm
  MooseX::AttributeHelpers::MethodProvider::Array:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Array.pm
    version: 0.02
  MooseX::AttributeHelpers::MethodProvider::Counter:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Counter.pm
    version: 0.02
  MooseX::AttributeHelpers::MethodProvider::Hash:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Hash.pm
    version: 0.01
  MooseX::AttributeHelpers::MethodProvider::List:
    file: lib/MooseX/AttributeHelpers/MethodProvider/List.pm
    version: 0.01
  MooseX::AttributeHelpers::Number:
    file: lib/MooseX/AttributeHelpers/Number.pm
    version: 0.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
