---
abstract: 'Extend your attribute interfaces'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-AttributeHelpers
no_index:
  directory:
    - inc
    - t
provides:
  MooseX::AttributeHelpers:
    file: lib/MooseX/AttributeHelpers.pm
    version: 0.12
  MooseX::AttributeHelpers::Base:
    file: lib/MooseX/AttributeHelpers/Base.pm
    version: 0.12
  MooseX::AttributeHelpers::Bool:
    file: lib/MooseX/AttributeHelpers/Bool.pm
    version: 0.12
  MooseX::AttributeHelpers::Collection:
    file: lib/MooseX/AttributeHelpers/Collection.pm
    version: 0.12
  MooseX::AttributeHelpers::Collection::Array:
    file: lib/MooseX/AttributeHelpers/Collection/Array.pm
    version: 0.12
  MooseX::AttributeHelpers::Collection::Bag:
    file: lib/MooseX/AttributeHelpers/Collection/Bag.pm
    version: 0.12
  MooseX::AttributeHelpers::Collection::Hash:
    file: lib/MooseX/AttributeHelpers/Collection/Hash.pm
    version: 0.12
  MooseX::AttributeHelpers::Collection::ImmutableHash:
    file: lib/MooseX/AttributeHelpers/Collection/ImmutableHash.pm
    version: 0.12
  MooseX::AttributeHelpers::Collection::List:
    file: lib/MooseX/AttributeHelpers/Collection/List.pm
    version: 0.12
  MooseX::AttributeHelpers::Counter:
    file: lib/MooseX/AttributeHelpers/Counter.pm
    version: 0.12
  MooseX::AttributeHelpers::Meta::Method::Curried:
    file: lib/MooseX/AttributeHelpers/Meta/Method/Curried.pm
  MooseX::AttributeHelpers::Meta::Method::Provided:
    file: lib/MooseX/AttributeHelpers/Meta/Method/Provided.pm
  MooseX::AttributeHelpers::MethodProvider::Array:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Array.pm
    version: 0.12
  MooseX::AttributeHelpers::MethodProvider::Bag:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Bag.pm
    version: 0.12
  MooseX::AttributeHelpers::MethodProvider::Bool:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Bool.pm
    version: 0.12
  MooseX::AttributeHelpers::MethodProvider::Counter:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Counter.pm
    version: 0.12
  MooseX::AttributeHelpers::MethodProvider::Hash:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Hash.pm
    version: 0.12
  MooseX::AttributeHelpers::MethodProvider::ImmutableHash:
    file: lib/MooseX/AttributeHelpers/MethodProvider/ImmutableHash.pm
    version: 0.12
  MooseX::AttributeHelpers::MethodProvider::List:
    file: lib/MooseX/AttributeHelpers/MethodProvider/List.pm
    version: 0.12
  MooseX::AttributeHelpers::MethodProvider::String:
    file: lib/MooseX/AttributeHelpers/MethodProvider/String.pm
    version: 0.12
  MooseX::AttributeHelpers::Number:
    file: lib/MooseX/AttributeHelpers/Number.pm
    version: 0.12
  MooseX::AttributeHelpers::String:
    file: lib/MooseX/AttributeHelpers/String.pm
    version: 0.12
requires:
  Moose: 0.45
version: 0.12
