---
abstract: 'Extend your attribute interfaces'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.21
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.89'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-AttributeHelpers
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.56
resources:
  license: http://dev.perl.org/licenses/
version: 0.18_01
