---
name: MooseX-AttributeHelpers
version: 0.05
author:
  - 'Stevan Little E<lt>stevan@iinteractive.comE<gt>'
abstract: Extend your attribute interfaces
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::MOP: 0.47
  Moose: 0.30
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
provides:
  MooseX::AttributeHelpers:
    file: lib/MooseX/AttributeHelpers.pm
    version: 0.05
  MooseX::AttributeHelpers::Base:
    file: lib/MooseX/AttributeHelpers/Base.pm
    version: 0.03
  MooseX::AttributeHelpers::Collection:
    file: lib/MooseX/AttributeHelpers/Collection.pm
    version: 0.03
  MooseX::AttributeHelpers::Collection::Array:
    file: lib/MooseX/AttributeHelpers/Collection/Array.pm
    version: 0.01
  MooseX::AttributeHelpers::Collection::Bag:
    file: lib/MooseX/AttributeHelpers/Collection/Bag.pm
    version: 0.01
  MooseX::AttributeHelpers::Collection::Hash:
    file: lib/MooseX/AttributeHelpers/Collection/Hash.pm
    version: 0.02
  MooseX::AttributeHelpers::Collection::ImmutableHash:
    file: lib/MooseX/AttributeHelpers/Collection/ImmutableHash.pm
    version: 0.01
  MooseX::AttributeHelpers::Collection::List:
    file: lib/MooseX/AttributeHelpers/Collection/List.pm
    version: 0.01
  MooseX::AttributeHelpers::Counter:
    file: lib/MooseX/AttributeHelpers/Counter.pm
    version: 0.03
  MooseX::AttributeHelpers::Meta::Method::Provided:
    file: lib/MooseX/AttributeHelpers/Meta/Method/Provided.pm
  MooseX::AttributeHelpers::MethodProvider::Array:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Array.pm
    version: 0.05
  MooseX::AttributeHelpers::MethodProvider::Bag:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Bag.pm
    version: 0.02
  MooseX::AttributeHelpers::MethodProvider::Counter:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Counter.pm
    version: 0.02
  MooseX::AttributeHelpers::MethodProvider::Hash:
    file: lib/MooseX/AttributeHelpers/MethodProvider/Hash.pm
    version: 0.03
  MooseX::AttributeHelpers::MethodProvider::ImmutableHash:
    file: lib/MooseX/AttributeHelpers/MethodProvider/ImmutableHash.pm
    version: 0.03
  MooseX::AttributeHelpers::MethodProvider::List:
    file: lib/MooseX/AttributeHelpers/MethodProvider/List.pm
    version: 0.01
  MooseX::AttributeHelpers::Number:
    file: lib/MooseX/AttributeHelpers/Number.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
